language: scala

jdk:
  - openjdk8
  - openjdk11

script:
  ## runs both regular tests and sbt-scripted integration tests
  - sbt -Dfile.encoding=UTF8 scalafmtCheckAll scalafmtSbtCheck test scripted

sudo: false

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
